name: ci

on:
  push  

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
      - name: Run CI
        run: deno task lint

      - name: Install deployctl
        run: deno install -Arf jsr:@deno/deployctl
        if: ${{ github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/') }}
      
      - name: Deploy to Deno Deploy preview
        run: deployctl deploy --project deno-googleapis-cli --entrypoint server/main.ts --token ${{ secrets.DENO_DEPLOY_TOKEN }}
        if: ${{ github.ref == 'refs/heads/main' }}
      
      - name: Deploy to Deno Deploy production
        run: deployctl deploy --project deno-googleapis-cli --entrypoint server/main.ts --prod --token ${{ secrets.DENO_DEPLOY_TOKEN }}
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
